AllCops:
  Exclude:
    - bin/*
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'lib/speechkit_bot/voice_handler.rb'

Metrics/BlockLength:
  Exclude:
    - spec/**/*
