---
version: '3'
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
    command: bin/bot
    volumes:
      - .:/ruby_app:cached
    depends_on:
      mongo:
        condition: service_started
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
