development:
  clients:
    default:
      database: bot_development
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: bot_test
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
